### ISSUE TITLE
Error while running sh scripts/train_pctnet.sh

### ISSUE THREAD

**Issue by ANJALI-PS** [rocketappslab/SCA-GAN#4]
Traceback (most recent call last):
File "train.py", line 19, in
model = create_model(opt)
File "/home/cse/SCA-GAN/models/models.py", line 13, in create_model
model.initialize(opt)
File "/home/cse/SCA-GAN/models/trainer_edge.py", line 68, in initialize
self.criterionL1 = L1_plus_perceptualLoss(opt.lambda_A, opt.lambda_B, opt.perceptual_layers, self.gpu_ids, opt.percep_is_l1)
File "/home/cse/SCA-GAN/losses/L1_plus_perceptualLoss.py", line 22, in init
vgg19.load_state_dict(torch.load('../../Dataset/PoseTransfer/ADGAN/vgg19-dcbb9e9d.pth'))
File "/home/cse/.local/lib/python3.8/site-packages/torch/serialization.py", line 525, in load
with _open_file_like(f, 'rb') as opened_file:
File "/home/cse/.local/lib/python3.8/site-packages/torch/serialization.py", line 212, in _open_file_like
return _open_file(name_or_buffer, mode)
File "/home/cse/.local/lib/python3.8/site-packages/torch/serialization.py", line 193, in init
super(_open_file, self).init(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '../../Dataset/PoseTransfer/ADGAN/vgg19-dcbb9e9d.pth'

**Comment by ANJALI-PS** [comment]
Traceback (most recent call last):
  File "train.py", line 19, in <module>
    model = create_model(opt)
  File "/home/cse/SCA-GAN/models/models.py", line 13, in create_model
    model.initialize(opt)
  File "/home/cse/SCA-GAN/models/trainer_edge.py", line 68, in initialize
    self.criterionL1 = L1_plus_perceptualLoss(opt.lambda_A, opt.lambda_B, opt.perceptual_layers, self.gpu_ids, opt.percep_is_l1)
  File "/home/cse/SCA-GAN/losses/L1_plus_perceptualLoss.py", line 22, in __init__
    vgg19.load_state_dict(torch.load('../../Dataset/PoseTransfer/ADGAN/vgg19-dcbb9e9d.pth'))
  File "/home/cse/.local/lib/python3.8/site-packages/torch/serialization.py", line 525, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/cse/.local/lib/python3.8/site-packages/torch/serialization.py", line 212, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/cse/.local/lib/python3.8/site-packages/torch/serialization.py", line 193, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '../../Dataset/PoseTransfer/ADGAN/vgg19-dcbb9e9d.pth'
